### ISSUE TITLE
Site redesign?

### ISSUE THREAD

**Issue by jaronoff97** [hacks/hacks.github.io#27]
Does anyone want to work on a site redesign? I know @ctbeiser was working on one, but I've also been asked by a couple of other people that they want to work on a redesign. Next meeting lets talk about this. @daniellenguyen @dan3944

**Comment by kylesferrazza** [comment]
I'm going to work on a cool redesign

**Comment by kylesferrazza** [comment]
So is @edward-shen

**Comment by jaronoff97** [comment]
CC @daniellenguyen ^^^

**Comment by edward-shen** [comment]
#31, #32, and #33 can likely all be incorporated into the new design, likely making them non-issues.
@kylesferrazza and I will be using Jekyll for our redesign.

Any specific requests? @aliceyoung9 @jaronoff97

**Comment by aliceyoung9** [comment]
(The low-hanging fruit issues are for a low barrier to entry for newbies/underclassmen who want to participate in Hacktoberfest.) I'm sure they're trivial enough that the rewrite will also take care of them too, but u know.

Jekyll's probably the right choice.

**Comment by edward-shen** [comment]
See #39.

**Comment by ctbeiser** [comment]
I did a series of mockups on this one. Apparently a recent version of Sketch messed up the files slightly (the saturation of the background is not supposed to change halfway down) but I think they're still useful as a stylistic reference. 

I've used an overly loose grid, and the sense of scale is very off, but I think in particular the fonts and colors are something that have a lot of resonance with what Hacks can be. See also the sketch file with 29 different revisions:
[draft 2.zip](https://github.com/hacks/hacks.github.io/files/1389187/draft.2.zip)


![tablet portrait copy 6](https://user-images.githubusercontent.com/614019/31637547-2db8c61a-b29d-11e7-8b33-f4c41b0a3606.png)
![tablet portrait copy 15](https://user-images.githubusercontent.com/614019/31637555-35a44a20-b29d-11e7-9073-f2e394a8e4c0.png)
![tablet portrait copy 25](https://user-images.githubusercontent.com/614019/31637566-41240eda-b29d-11e7-9fce-c1891ba534e5.png)
![tablet portrait copy 26](https://user-images.githubusercontent.com/614019/31637569-4482f898-b29d-11e7-8f23-e93ca1061ca9.png)
![tablet portrait copy 27](https://user-images.githubusercontent.com/614019/31637570-449e6b00-b29d-11e7-991c-c20781dab9f1.png)

**Comment by sudopluto** [comment]
I kinda like the idea of a beige and purple color scheme, reminds me of the emacs and gentoo websites.
