### ISSUE TITLE
Clean Up Descriptions Page

### ISSUE THREAD

**Issue by aceyoung9** [hacks/hacks.github.io#44]
on testimonies.html

## Acceptance criteria
- [x] link from homepage should not have `target="_blank"` attribute.
- [x] Add in new font styles to match homepage (see #41)
- [x] Remove * characters from the bullet points
- [ ] remove crappy 4chan joke

**Comment by NEUDitao** [comment]
can we close it?

**Comment by dmelcer9** [comment]
> [] remove crappy 4chan joke

What to replace it with, a crappy Reddit joke?
